# Generated by Django 2.0.1 on 2018-01-21 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('picture', models.ImageField(blank=True, upload_to='media/profilepics/')),
                ('home', models.CharField(blank=True, max_length=100)),
                ('interests', models.CharField(blank=True, max_length=200)),
                ('objectives', models.CharField(blank=True, max_length=200)),
                ('joined', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('bio', tinymce.models.HTMLField()),
            ],
        ),
    ]
